cask_args appdir: "/Applications"

# Taps
tap "FelixKratz/formulae"

# Casks
cask "google-chrome"
cask "bitwarden"
cask "linearmouse"
cask "font-fira-code-nerd-font"
cask "raycast"
cask "nikitabobko/tap/aerospace"
cask "visual-studio-code"
cask "obsidian"
cask "ghostty"
cask "claude-code"
cask "stats"
cask "claude"

# Brews
brew "curl"
brew "wget"
brew "git"
brew "gh"
brew "tmux"
brew "stow"
brew "pyenv"
brew "neovim"
brew "direnv"
brew "pipx"
brew "uv"
brew "poetry"
brew "pre-commit"
brew "antidote"
brew "rg"
brew "gpg"
brew "fd"
brew "tmuxinator"
brew "tpm"
brew "node"
brew "zoxide"
brew "lazygit"
brew "luarocks"
brew "fzf"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "opencode"
brew "borders"
