cask_args appdir: "/Applications"

# Taps
tap "homebrew/bundle"

# Casks
cask "visual-studio-code"
cask "spotify"
cask "google-chrome"
cask "1password"
cask "bitwarden"
cask "rectangle"
cask "slack"
cask "linearmouse"
cask "notion"
cask "font-fira-code-nerd-font"
cask "cursor"
cask "raycast"
cask "wezterm"
cask "orbstack"
cask "nikitabobko/tap/aerospace"
cask "gitify"
cask "1password-cli"
cask "pgadmin4"

# Brews
brew "curl"
brew "wget"
brew "git"
brew "gh"
brew "tmux"
brew "stow"
brew "pyenv"
brew "neovim"
brew "direnv"
brew "pipx"
brew "uv"
brew "poetry"
brew "pre-commit"
brew "antidote"
brew "rg"
